=== Joonas-M-S/digitraffic-road/src/main/resources/schemas/tloik/ims/jmessage/simppeli-situation_v0_2.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"title": "TrafficSituation announcement.",
	"description": "Structural representation of a traffic situation containing its key elements and all the language versions of announcements sent by Finnish Transportation Agency.",
	"properties": {
		"situtationId": {
			"type": "string",
			"required" : true
		},
		"version": {
			"type": "integer",
			"required" : true
		},
		"releaseTime": {
			"type": "string",
			"description": "Annouchment release time.",
			"required" : true
		},
		"locationToDisplay": {
			"type": "object",
			"title": "LocationToDisplay schema.",
			"description": "Locatin to display in ETRS-TM35FIN coordinate format.",
			"properties": {
				"E": {
					"type": "number"
				},
				"N": {
					"type": "number"
				}
			}
		},
		"announcements": {
			"type": "array",
			"title": "Announcements schema.",
			"description": "Contains announcement's different language versions available.",
			"items": {
				"type": "object",
				"$ref": "simppeli-announcement_v0_1.schema.json",
				"required": true
			},
			"required": true
		},
		"contact": {
			"type": "object",
			"title": "Contact schema.",
			"description": "Sender's contact information.",
			"properties": {
				"phone": {
					"type": "string",
					"title": "Phone schema."
				},
				"fax": {
					"type": "string",
					"title": "Fax schema."
				},
				"email": {
					"type": "string",
					"title": "Email schema."
				}
			}	
		}
	}
}

=== Joonas-M-S/digitraffic-road/src/main/resources/schemas/tloik/ims/jmessage/simppeli-esimerkki_v0_2.json
{
	"situtationId": "GUID123456789",
	"version": 1,
	"releaseTime": "2014-06-24T15:34:10+03:00",
	"locationToDisplay": {
		"E": 222327,
		"N": 6827610
	},
	"announcements": [
		{
			"language": "fi",
			"title": "Liikennetiedote",
			"location": {
				"countrycode": 6,
				"locationtablenumber": 17,
				"locationtableversion": "1.11.37",
				"description": "Tie 23 välillä Pori - Jyväskylä, Keuruu. Tarkempi paikka: Paikasta Kaleton 3,6 km, vaikutusalue 1,6 km, suuntaan Jutkala.",
				"primarypoint": {
					"municipality": "Keuruu",
					"province": "Keski-Suomi",
					"country": "Finland",
					"roadAddress": {
						"road": 23,
						"roadSection": 221,
						"distance": 3616
					},
					"roadName": "Jyväskyläntie",
					"alertclocation": {
						"locationcode": 2428,
						"name": "Kaleton",
						"distance": 3616
					}
				},
				"secondarypoint": {
					"municipality": "Keuruu",
					"province": "Keski-Suomi",
					"country": "Finland",
					"roadAddress": {
						"road": 23,
						"roadSection": 222,
						"distance": 188
					},
					"roadName": "Jyväskyläntie",
					"alertclocation": {
						"locationcode": 2431,
						"name": "Jutkala",
						"distance": 15333
					}
				},
				"direction": "positive",
				"directionDescription": "Jutkala"
			},
			"features": [
				"Yksi ajokaista on suljettu liikenteeltä",
				"Tie tai tien reuna on painunut",
				"Paikalla tilapäinen liikennevalo-ohjaus"
			],
			"comment": "Ruuhka-aikaan liikenne saattaa jonoutua liikennevalojen takia.",
			"timeAndDuration": {
				"startTime": "2014-06-24T15:34:10+03:00"
			},
			"additionalInformation": "Liikenne- ja kelitietoa myös www.liikennevirasto.fi/alk",
			"sender": "Liikenneviraston tieliikennekeskus Oulu"
		}
	],
	"contact": {
		"phone": "0206373331",
		"fax": "0206373710",
		"email": "oulu.liikennekeskus@liikennevirasto.fi"
	}
}
